# Generated by Django 4.1.6 on 2023-10-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsustain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuarioxfamilia',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='usuarioxfamilia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Objetivo',
        ),
        migrations.DeleteModel(
            name='UsuarioXFamilia',
        ),
    ]
