# Generated by Django 4.2.7 on 2023-11-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsustain', '0002_categoria_familia_usuarioxfamilia_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioxfamilia',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
