# Generated by Django 4.1.6 on 2023-10-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsustain', '0002_remove_notificacion_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha',
        ),
    ]
