# Generated by Django 4.1.6 on 2023-10-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsustain', '0003_remove_movimiento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha',
            field=models.CharField(default='13/10/2023', max_length=20),
            preserve_default=False,
        ),
    ]
